# Generated by Django 5.1.1 on 2025-01-01 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
