# Generated by Django 5.1.1 on 2025-01-11 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_litcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coins',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
