# Generated by Django 5.1.1 on 2025-01-11 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rentsbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentsbook',
            name='end_rent',
            field=models.DateField(default=datetime.datetime(2025, 2, 10, 15, 2, 58, 858555)),
        ),
        migrations.AddField(
            model_name='rentsbook',
            name='start_rent',
            field=models.DateField(default=datetime.date(2025, 1, 11)),
        ),
    ]
