# Generated by Django 5.1.1 on 2025-01-11 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_rentsbook_end_rent_rentsbook_start_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsbook',
            name='end_rent',
            field=models.DateField(default=datetime.datetime(2025, 2, 10, 15, 7, 43, 862559)),
        ),
    ]
