# Generated by Django 5.1.1 on 2025-01-14 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_rentsbook_end_rent_alter_rentsbook_start_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsbook',
            name='end_rent',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 13, 2, 49, 636267)),
        ),
    ]
