# Generated by Django 5.1.1 on 2025-01-14 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_rentsbook_end_rent_alter_tg_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsbook',
            name='end_rent',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 16, 59, 40, 512471)),
        ),
    ]
