# Generated by Django 5.1.1 on 2025-01-14 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_rentsbook_end_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsbook',
            name='end_rent',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 17, 0, 30, 111881)),
        ),
    ]
