# Generated by Django 5.1.1 on 2025-01-14 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_alter_rentsbook_end_rent_delete_tg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsbook',
            name='end_rent',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 17, 19, 9, 136007)),
        ),
    ]
