# Generated by Django 5.1.1 on 2025-01-14 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_alter_rentsbook_end_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='agreement_of_the_willing',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='host_agreement',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='end_rent',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 17, 46, 17, 271331)),
        ),
    ]
