# Generated by Django 5.1.1 on 2025-01-14 17:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_book_agreement_of_the_willing_book_host_agreement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='agreement_of_the_willing',
        ),
        migrations.RemoveField(
            model_name='book',
            name='host_agreement',
        ),
        migrations.AddField(
            model_name='rentsbook',
            name='agree_one',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='rentsbook',
            name='agree_two',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='rentsbook',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books_author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentsbook',
            name='in_rent',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='end_rent',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 17, 52, 24, 425606)),
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
