# Generated by Django 5.1.1 on 2025-01-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_remove_book_agreement_of_the_willing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsbook',
            name='end_rent',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='start_rent',
            field=models.DateField(),
        ),
    ]
