# Generated by Django 5.1.1 on 2025-01-14 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_alter_rentsbook_end_rent_alter_rentsbook_start_rent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentsbook',
            name='author',
        ),
        migrations.AddField(
            model_name='rentsbook',
            name='arendator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books_arendator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
