# Generated by Django 5.1.1 on 2025-01-14 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_remove_rentsbook_author_rentsbook_arendator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsbook',
            name='end_rent',
            field=models.DateField(default=datetime.datetime(4762, 12, 11, 18, 14, 23, 299480)),
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='start_rent',
            field=models.DateField(default=datetime.date(2025, 1, 14)),
        ),
    ]
