# Generated by Django 5.1.1 on 2025-01-23 21:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_alter_rentsbook_end_rent_alter_rentsbook_start_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litcoin',
            name='coins',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='end_rent',
            field=models.DateField(default=datetime.date(4762, 12, 20)),
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='start_rent',
            field=models.DateField(default=datetime.date(2025, 1, 23)),
        ),
    ]
