# Generated by Django 5.1.1 on 2025-02-05 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_alter_litcoin_coins_alter_rentsbook_end_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsbook',
            name='end_rent',
            field=models.DateField(default=datetime.date(4763, 1, 2)),
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='start_rent',
            field=models.DateField(default=datetime.date(2025, 2, 5)),
        ),
    ]
